const List<Map<String, String>> predefinedAppliances = [
  {'name': 'Air Conditioner (1 Ton)', 'wattage': '1200'},
  {'name': 'Air Conditioner (1.5 Ton)', 'wattage': '1800'},
  {'name': 'Blender/Mixer', 'wattage': '400'},
  {'name': 'Ceiling Fan', 'wattage': '75'},
  {'name': 'CFL Bulb', 'wattage': '15'},
  {'name': 'Deep Freezer', 'wattage': '200'},
  {'name': 'Desktop Computer', 'wattage': '200'},
  {'name': 'Electric Kettle', 'wattage': '1500'},
  {'name': 'Exhaust Fan', 'wattage': '40'},
  {'name': 'Hair Dryer', 'wattage': '1000'},
  {'name': 'Inverter AC (1.5 Ton)', 'wattage': '1200–1500'},
  {'name': 'Iron', 'wattage': '1000'},
  {'name': 'Laptop Charger', 'wattage': '65'},
  {'name': 'LCD/LED TV (50")', 'wattage': '100'},
  {'name': 'LED Bulb (9W)', 'wattage': '9'},
  {'name': 'Microwave Oven', 'wattage': '1200'},
  {'name': 'Mobile Charger', 'wattage': '5'},
  {'name': 'Others', 'wattage': ''},
  {'name': 'Pedestal/Table Fan', 'wattage': '50'},
  {'name': 'Refrigerator (Medium)', 'wattage': '150'},
  {'name': 'Television (32")', 'wattage': '60'},
  {'name': 'Toaster', 'wattage': '800'},
  {'name': 'Tube Light (LED)', 'wattage': '18'},
  {'name': 'Vacuum Cleaner', 'wattage': '800'},
  {'name': 'Washing Machine', 'wattage': '500'},
  {'name': 'Water Dispenser', 'wattage': '100'},
  {'name': 'Water Motor (0.5 HP)', 'wattage': '375'},
  {'name': 'Wi-Fi Router', 'wattage': '10'},
];
